# https://github.com/jest-community/eslint-plugin-jest
plugins:
  - jest

# Правильный способ включения поддержки глобальных идентификаторов
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  jest: true
  es2020: true

extends:
  - airbnb-base
  - "plugin:jest/recommended"

# Включает поддержку конструкции import.meta.url
parserOptions:
  ecmaVersion: 2020

rules:
  no-console: 0
  import/extensions: 0